version: '3'

services:
  app:
    build: .
    # network_mode: "host" #Habilita la conectividad del host
    container_name: fastapi
    ports:
      - "8080:80"    
    volumes: 
      - type: bind
        source: ./app
        target: /app
      - type: bind
        source: //c/Jose/Data
        target: /app/data
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 80 --workers 1 --reload
